## Travis-CI YAML to publish worldwind-react-app to GitHub Pages
language: node_js
node_js:
  - "stable"
script:
#  - npm test
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_API_KEY
  local_dir: build
  on:
    branch: master